name: artroad
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  table_calendar: ^3.0.6
  card_swiper: ^3.0.1
  provider: ^5.0.0
  fluttertoast: ^8.0.8
  android_intent_plus: ^4.0.2
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Oleo Script Swash Caps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCapsRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
